version: '3.5'

volumes:
  postgres-data:
  redis-data:
networks:
  mybike-net:

services:
  postgres:
    container_name: mybike_postgres
    image: postgres:14.0
    env_file: .env
    ports:
      - 5439:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mybike-net

  redis:
    container_name: mybike_redis
    image: redis:latest
    entrypoint: redis-server --appendonly yes
    ports:
      - 6389:6379
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - mybike-net
